### PR TITLE
Add windows support

### LINKED ISSUE #5: how to install atari-py in windows?
i installed gnuwin, cmake for make, cmake command.

 make: Entering directory `C:/Users/ADMINI~1/AppData/Local/Temp/pip-build-i8domwa1/atari-py/atari_py/ale_interface'
  mkdir -p build && cd build && cmake .. && make -j4
  -- Building for: Visual Studio 14 2015
  -- The C compiler identification is unknown
  -- The CXX compiler identification is unknown
  CMake Error at CMakeLists.txt:2 (project):
    No CMAKE_C_COMPILER could be found.

i can't find this problem's solution.

i can't inglish well. sorry.  :3

### PR DESCRIPTION
**Pull request by Kojoley**
Tested with Python 2.7/VS for Python 2.7 and 3.5/VS 2015

Closes #5

### CODE REVIEW

**Comment by Kojoley** [comment]
It looks like I've broke the linux build. I'll try to fix.

**Comment by sharpe5** [comment]
Would be fantastic if this pull request could be merged, it would have saved me days of time if I had discovered this earlier!

**Comment by Kojoley** [comment]
This is actually an obsolete PR as I have removed `zlib` dependency too (check my fork).

**Comment by timotei** [comment]
@Kojoley Any particular reason why not merge it in original repo? Doesn't make much sense to have a totally separate fork just for windows 🤔 

I see you removed the zlib/libpng deps, but if they're really not needed on windows I don't see a problem with that.

**Comment by Kojoley** [comment]
> Any particular reason why not merge it in original repo?

Somebody have to push merge button, it could have be done for two years already, but as you might see there is no even a comment.

**Comment by timotei** [comment]
@pzhokhov @christopherhesse Could you please take a look and merge this PR so us, the windows users could benefit of it? Thank you!

**Comment by christopherhesse** [comment]
This looks great @Koholey!  Sorry for not seeing this earlier.  It would be great to have windows support for atari-py (this is one reason dopamine does not work easily on windows for instance).  I haven't looked at the changes in detail, but the main thing lacking for me is a windows build in travis (https://blog.travis-ci.com/2018-10-11-windows-early-release) so that we can tell when a change breaks the windows build.

In addition, windows users don't usually have cmake or anything, and we already build wheels for mac and linux so if the travis windows build also did wheels that would be amazing, but that can be done in a different PR.

**Comment by Kojoley** [comment]
> It would be great to have windows support for atari-py

We have it https://stackoverflow.com/a/46739299/3621421. What we don't have is wheels on PyPI.

> windows build in travis

My fork uses Appveyor for building wheels (there was no Windows support on Travis at that time). I do not think there is anything preventing you adding a Travis Windows job.

> In addition, windows users don't usually have cmake or anything

I removed usage of `cmake`, `libpng`, and `zlib` in my fork 2 years ago.

**Comment by christopherhesse** [comment]
We can look into the travis windows thing, would you be fine with re-opening this PR?

**Comment by christopherhesse** [comment]
We did this in a different PR: https://github.com/openai/atari-py/pull/50  thanks for making this PR though!

**Pull request closed without merging**
