### PR TITLE
Version bump to v0.2.0

### PR DESCRIPTION
**Pull request by JesseFarebro**

### CODE REVIEW

**Comment by JesseFarebro** [comment]
Pinging @christopherhesse. We can now perform the version bump with #53 in place.

**Comment by christopherhesse** [comment]
Thanks!  @pzhokhov will most likely look at this tomorrow

**Comment by christopherhesse** [comment]
Or sooner

**Comment by JesseFarebro** [comment]
Thanks for the prompt responses @christopherhesse and @pzhokhov! 😄

**Pull request merged**
