### PR TITLE
Gentoo zconf.h OF define fix.

### PR DESCRIPTION
**Pull request by BlGene**
Probably not an issue for most people, but in case somebody has trouble.

### CODE REVIEW

**Comment by dargor** [comment]
Works for me on Gentoo :+1:

**Comment by zamlz** [comment]
Whats the hold up on this pull request?

**Comment by christopherhesse** [comment]
Closing in favor of https://github.com/openai/atari-py/pull/45

**Comment by christopherhesse** [comment]
Thanks for the fix @BlGene!

**Pull request closed without merging**
