### PR TITLE
Fix switch fall-through in Gravitor.cpp

### PR DESCRIPTION
**Pull request by lespeholt**

### CODE REVIEW

**Comment by JesseFarebro** [comment]
Good catch! If you don’t mind could you also submit this upstream to: https://github.com/mgbellemare/Arcade-Learning-Environment

**Comment by lespeholt** [comment]
Done: https://github.com/mgbellemare/Arcade-Learning-Environment/pull/264

**Comment by christopherhesse** [comment]
Thanks!

**Comment by lespeholt** [comment]
Shouldn't the patch have been accepted?

**Comment by christopherhesse** [comment]
I think you're asking if we should update our copy from upstream, and yes, we should.

**Comment by JesseFarebro** [comment]
@christopherhesse would you be open to having the ALE as a git submodule so we can more easily track and update from upstream. If so I can make this happen.

**Comment by christopherhesse** [comment]
Thanks for the offer @JesseFarebro!  I was thinking something similar: https://github.com/openai/atari-py/issues/67

**Pull request closed without merging**
